import React, { useEffect, useState } from 'react';
import api from '../../utils/api';
import { useToast } from '../Toasts/useToast';
import { Save, Cpu, AlertTriangle, CheckCircle } from '../../icons';
import '../DeckyFleet.css';
import '../PersonaGeneration.css';
import './LLMConfig.css';

// ─── Types ───────────────────────────────────────────────────────────────────

interface LLMConfigPayload {
  provider: string;
  base_url: string | null;
  model: string;
  timeout: number;
  api_key_set: boolean;
}

interface PutBody {
  provider?: string;
  base_url?: string | null;
  model?: string;
  timeout?: number;
  api_key?: string;
}

const DEFAULTS: LLMConfigPayload = {
  provider: 'ollama',
  base_url: null,
  model: 'llama3.1',
  timeout: 60,
  api_key_set: false,
};

// ─── Page ────────────────────────────────────────────────────────────────────

const LLMConfig: React.FC = () => {
  const { push } = useToast();
  const [config, setConfig] = useState<LLMConfigPayload>(DEFAULTS);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [apiKeyInput, setApiKeyInput] = useState('');
  const [clearApiKey, setClearApiKey] = useState(false);

  const fetchConfig = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await api.get<LLMConfigPayload>('/realism/llm');
      setConfig(res.data);
    } catch (err: any) {
      setError(err?.response?.status === 401 ? 'Authentication required.' : 'Load failed.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchConfig(); }, []);

  const handleSave = async () => {
    setSaving(true);
    setError(null);
    try {
      const body: PutBody = {
        provider: config.provider,
        base_url: config.base_url || null,
        model: config.model,
        timeout: config.timeout,
      };
      if (clearApiKey) {
        body.api_key = '';
      } else if (apiKeyInput.trim()) {
        body.api_key = apiKeyInput.trim();
      }

      const res = await api.put<LLMConfigPayload>('/realism/llm', body);
      setConfig(res.data);
      setApiKeyInput('');
      setClearApiKey(false);
      push({ text: 'LLM CONFIG SAVED', tone: 'matrix', icon: 'terminal' });
    } catch (err: any) {
      const detail = err?.response?.data?.detail;
      const status = err?.response?.status;
      if (status === 403) setError('Admin role required to save.');
      else if (status === 400 && detail) setError(`Validation failed: ${detail}`);
      else setError('Save failed.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="fleet-root llm-config-root">
      <div className="page-header">
        <div className="page-title-group">
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <Cpu size={22} className="violet-accent" />
            <h1>LLM PROVIDER CONFIG</h1>
          </div>
          <span className="page-sub">
            {config.provider.toUpperCase()} · {config.model}
            {config.base_url ? ` · ${config.base_url}` : ' · subprocess'}
          </span>
        </div>
        <div className="actions">
          <button
            className="btn violet"
            onClick={handleSave}
            disabled={saving || loading}
            title="Persist and hot-reload the LLM backend; orchestrator picks it up within one tick."
          >
            <Save size={12} /> {saving ? 'SAVING…' : 'SAVE'}
          </button>
        </div>
      </div>

      <div className="info-banner">
        <div>
          <strong>Scope:</strong> configures the LLM backend used for{' '}
          <em>email bodies, drafts, and notes</em> generated by the realism
          subsystem. Changes are persisted to{' '}
          <span className="mono matrix-text">realism_config</span> and
          hot-reloaded in this API process immediately; the orchestrator worker
          picks them up within one refresh tick (~5 minutes).
        </div>
        {error && (
          <div className="info-line alert-text" style={{ marginTop: 8 }}>
            <AlertTriangle size={12} /> {error}
          </div>
        )}
      </div>

      {loading ? (
        <div className="dim" style={{ padding: '24px 0' }}>Loading…</div>
      ) : (
        <>
          <div className="section-head">Provider</div>

          <div className="form-grid">
            <div className="tweak-group">
              <label>Provider</label>
              <select
                className="input"
                value={config.provider}
                onChange={(e) => setConfig({ ...config, provider: e.target.value })}
              >
                <option value="ollama">Ollama</option>
              </select>
            </div>

            <div className="tweak-group">
              <label>Model</label>
              <input
                className="input"
                type="text"
                placeholder="llama3.1"
                value={config.model}
                onChange={(e) => setConfig({ ...config, model: e.target.value })}
              />
            </div>
          </div>

          <div className="form-grid single-col" style={{ marginBottom: 16 }}>
            <div className="tweak-group">
              <label>Base URL</label>
              <input
                className="input"
                type="url"
                placeholder="http://127.0.0.1:11434 — leave blank for local subprocess"
                value={config.base_url || ''}
                onChange={(e) =>
                  setConfig({ ...config, base_url: e.target.value || null })
                }
              />
            </div>
          </div>

          <div className="form-grid">
            <div className="tweak-group">
              <label>Timeout (seconds)</label>
              <input
                className="input"
                type="number"
                min={1}
                step={1}
                value={config.timeout}
                onChange={(e) => {
                  const v = parseFloat(e.target.value);
                  if (v > 0) setConfig({ ...config, timeout: v });
                }}
              />
            </div>

            <div className="tweak-group">
              <label>API Key (write-only)</label>
              {config.api_key_set && !clearApiKey ? (
                <>
                  <div className="key-badge">
                    <CheckCircle size={11} /> KEY SET — enter a new value to rotate, or
                    <button
                      className="btn ghost"
                      style={{ padding: '2px 8px', fontSize: '0.65rem', marginLeft: 6 }}
                      onClick={() => { setClearApiKey(true); setApiKeyInput(''); }}
                    >
                      CLEAR
                    </button>
                  </div>
                </>
              ) : (
                <>
                  <input
                    className="input"
                    type="password"
                    placeholder={clearApiKey ? '(will be cleared on save)' : 'Enter key to set, leave blank to keep unchanged'}
                    value={apiKeyInput}
                    disabled={clearApiKey}
                    onChange={(e) => setApiKeyInput(e.target.value)}
                  />
                  {clearApiKey && (
                    <button
                      className="btn ghost"
                      style={{ padding: '2px 8px', fontSize: '0.65rem', marginTop: 4, alignSelf: 'flex-start' }}
                      onClick={() => setClearApiKey(false)}
                    >
                      CANCEL CLEAR
                    </button>
                  )}
                </>
              )}
            </div>
          </div>
        </>
      )}
    </div>
  );
};

export default LLMConfig;
